package com.example.studyapp.entity;

import java.util.Date;

public class TaskInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.task_id
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.task_title
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    private String taskTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.user_id
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.task_deadline
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    private Date taskDeadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.task_status
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    private String taskStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.created_at
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.delete_flg
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    private Integer deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.task_description
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    private String taskDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.task_id
     *
     * @return the value of task_info.task_id
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.task_id
     *
     * @param taskId the value for task_info.task_id
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.task_title
     *
     * @return the value of task_info.task_title
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    public String getTaskTitle() {
        return taskTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.task_title
     *
     * @param taskTitle the value for task_info.task_title
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    public void setTaskTitle(String taskTitle) {
        this.taskTitle = taskTitle == null ? null : taskTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.user_id
     *
     * @return the value of task_info.user_id
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.user_id
     *
     * @param userId the value for task_info.user_id
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.task_deadline
     *
     * @return the value of task_info.task_deadline
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    public Date getTaskDeadline() {
        return taskDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.task_deadline
     *
     * @param taskDeadline the value for task_info.task_deadline
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    public void setTaskDeadline(Date taskDeadline) {
        this.taskDeadline = taskDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.task_status
     *
     * @return the value of task_info.task_status
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.task_status
     *
     * @param taskStatus the value for task_info.task_status
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    public void setTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus == null ? null : taskStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.created_at
     *
     * @return the value of task_info.created_at
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.created_at
     *
     * @param createdAt the value for task_info.created_at
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.delete_flg
     *
     * @return the value of task_info.delete_flg
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    public Integer getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.delete_flg
     *
     * @param deleteFlg the value for task_info.delete_flg
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    public void setDeleteFlg(Integer deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.task_description
     *
     * @return the value of task_info.task_description
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    public String getTaskDescription() {
        return taskDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.task_description
     *
     * @param taskDescription the value for task_info.task_description
     *
     * @mbg.generated Mon Feb 17 09:24:03 JST 2025
     */
    public void setTaskDescription(String taskDescription) {
        this.taskDescription = taskDescription == null ? null : taskDescription.trim();
    }
}