package com.example.studyapp.entity_gen;

import java.util.Date;

public class TaskInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.task_id
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    private Integer task_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.task_title
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    private String task_title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.user_id
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.task_deadline
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    private Date task_deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.task_status
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    private String task_status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.created_at
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    private Date created_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.delete_flg
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    private Integer delete_flg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.task_description
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    private String task_description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.task_id
     *
     * @return the value of task_info.task_id
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    public Integer getTask_id() {
        return task_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.task_id
     *
     * @param task_id the value for task_info.task_id
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    public void setTask_id(Integer task_id) {
        this.task_id = task_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.task_title
     *
     * @return the value of task_info.task_title
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    public String getTask_title() {
        return task_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.task_title
     *
     * @param task_title the value for task_info.task_title
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    public void setTask_title(String task_title) {
        this.task_title = task_title == null ? null : task_title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.user_id
     *
     * @return the value of task_info.user_id
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.user_id
     *
     * @param user_id the value for task_info.user_id
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.task_deadline
     *
     * @return the value of task_info.task_deadline
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    public Date getTask_deadline() {
        return task_deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.task_deadline
     *
     * @param task_deadline the value for task_info.task_deadline
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    public void setTask_deadline(Date task_deadline) {
        this.task_deadline = task_deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.task_status
     *
     * @return the value of task_info.task_status
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    public String getTask_status() {
        return task_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.task_status
     *
     * @param task_status the value for task_info.task_status
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    public void setTask_status(String task_status) {
        this.task_status = task_status == null ? null : task_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.created_at
     *
     * @return the value of task_info.created_at
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.created_at
     *
     * @param created_at the value for task_info.created_at
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.delete_flg
     *
     * @return the value of task_info.delete_flg
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    public Integer getDelete_flg() {
        return delete_flg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.delete_flg
     *
     * @param delete_flg the value for task_info.delete_flg
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    public void setDelete_flg(Integer delete_flg) {
        this.delete_flg = delete_flg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.task_description
     *
     * @return the value of task_info.task_description
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    public String getTask_description() {
        return task_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.task_description
     *
     * @param task_description the value for task_info.task_description
     *
     * @mbg.generated Sun Feb 16 18:11:00 JST 2025
     */
    public void setTask_description(String task_description) {
        this.task_description = task_description == null ? null : task_description.trim();
    }
}