package com.example.studyapp.mapper_gen;

import com.example.studyapp.entity_gen.TaskInfo;
import com.example.studyapp.entity_gen.TaskInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sun Feb 16 18:26:41 JST 2025
     */
    long countByExample(TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sun Feb 16 18:26:41 JST 2025
     */
    int deleteByExample(TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sun Feb 16 18:26:41 JST 2025
     */
    int deleteByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sun Feb 16 18:26:41 JST 2025
     */
    int insert(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sun Feb 16 18:26:41 JST 2025
     */
    int insertSelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sun Feb 16 18:26:41 JST 2025
     */
    List<TaskInfo> selectByExampleWithBLOBs(TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sun Feb 16 18:26:41 JST 2025
     */
    List<TaskInfo> selectByExample(TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sun Feb 16 18:26:41 JST 2025
     */
    TaskInfo selectByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sun Feb 16 18:26:41 JST 2025
     */
    int updateByExampleSelective(@Param("record") TaskInfo record, @Param("example") TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sun Feb 16 18:26:41 JST 2025
     */
    int updateByExampleWithBLOBs(@Param("record") TaskInfo record, @Param("example") TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sun Feb 16 18:26:41 JST 2025
     */
    int updateByExample(@Param("record") TaskInfo record, @Param("example") TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sun Feb 16 18:26:41 JST 2025
     */
    int updateByPrimaryKeySelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sun Feb 16 18:26:41 JST 2025
     */
    int updateByPrimaryKeyWithBLOBs(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sun Feb 16 18:26:41 JST 2025
     */
    int updateByPrimaryKey(TaskInfo record);
}